# Prompt theme
PROMPT_THEME='default'

# What modules to load configuration for
MODULES=(                                                            
    'environment'
    'terminal'
    'history' 
    'directories' 
    'colors' 
    'utils'
    'completion' 
    'prompt'   
)  

for MODULE in ${MODULES[@]}; do
    moduleConfig="${ZDOTDIR:-$HOME}/.zsh-config/$MODULE/config.zsh" 
    if [[ -s "$moduleConfig" ]]; then
        source "$moduleConfig"
    fi
done

# What tools to enable 
TOOLS=(                                                            
    'python/virtualenvwrapper'
)

for TOOL in ${TOOLS[@]}; do
    toolConfig="${ZDOTDIR:-$HOME}/.zsh-config/tools/$TOOL/config.zsh" 
    if [[ -s "$toolConfig" ]]; then
        source "$toolConfig"
    fi
done
