# Prompt theme
PROMPT_THEME='default'

# What modules to load configuration for
MODULES=(                                                            
    'environment'
    'terminal'
    'history' 
    'directories' 
    'colors' 
    'utils'
    'completion' 
    'prompt'   
)  

for MODULE in ${MODULES[@]}; do
    moduleConfig="${ZDOTDIR:-$HOME}/.zsh-config/$MODULE/config.zsh" 
    if [[ -s "$moduleConfig" ]]; then
        source "$moduleConfig"
    fi
done
